// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vladwithcode/sibra-site/internal/db"
import "fmt"

func cmpStr(str1, str2 string) bool {
	return str1 == str2
}

func EditProperty(property *db.Property) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h2 class=\"text-lg\">Actualizar Propiedad</h2><div class=\"py-2\"></div><div class=\"flex gap-2\"><form hx-put=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("/api/properties/" + property.Id)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 15, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"outerHTML\" class=\"relative shadow-md shadow-stone-300\" id=\"new-property_form\"><div class=\"absolute inset-0 bg-slate-700 opacity-60 hidden items-center justify-center rounded\" id=\"loading-spinner\"><svg class=\"fill-slate-300 w-16 h-16 mx-auto animate-spin\"><use href=\"/static/svg/spinner.svg#spinner\"></use></svg><p class=\"text-xl font-semibold text-slate-300\">Cargando...</p></div><h3 class=\"font-bold text-slate-700\">Informacion de la propiedad</h3><div class=\"flex gap-2\"><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"address\" class=\"block text-xs text-slate-400 font-semibold\">Domicilio</label> <input type=\"text\" name=\"address\" id=\"address\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"Gral. Anaya #101 int 4\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(property.Address)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 30, Col: 180}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"nbHood\" class=\"block text-xs text-slate-400 font-semibold\">Colonia/Fracc.</label> <input type=\"text\" name=\"nbHood\" id=\"nbHood\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"Col. Juan de la Barrera\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(property.NbHood)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 35, Col: 178}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div></div><div class=\"flex gap-2\"><div class=\"basis-full grow-0 space-y-1\"><label for=\"description\" class=\"block text-xs text-slate-400 font-semibold\">Descripción</label> <input type=\"text\" name=\"description\" id=\"description\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"Casa de 2 pisos con fachada naranja. 2 habitaciones y 1 baño.\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(property.Description)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 42, Col: 232}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div></div><div class=\"flex gap-2\"><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"city\" class=\"block text-xs text-slate-400 font-semibold\">Ciudad</label> <input type=\"text\" name=\"city\" id=\"city\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"Durango\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(property.City)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 49, Col: 156}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"state\" class=\"block text-xs text-slate-400 font-semibold\">Estado</label> <input type=\"text\" name=\"state\" id=\"state\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"Durango\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(property.State)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 54, Col: 159}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"zip\" class=\"block text-xs text-slate-400 font-semibold\">Código Postal</label> <input type=\"text\" name=\"zip\" id=\"zip\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"34158\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(property.Zip)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 59, Col: 151}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div></div><div class=\"flex gap-2\"><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"country\" class=\"block text-xs text-slate-400 font-semibold\">País</label> <input type=\"text\" name=\"country\" id=\"country\" class=\"w-full border border-slate-200 rounded px-2 py-1\" placeholder=\"México\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(property.Country)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 66, Col: 165}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></div><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"price\" class=\"block text-xs text-slate-400 font-semibold\">Precio</label> <input type=\"text\" name=\"price\" id=\"price\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"2_800_000\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%2f", property.Price))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 71, Col: 206}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required><p class=\"text-xs font-bold text-slate-400\">Si necesitas separar los números puedes hacerlo con '_' (ej. 2_000)</p></div></div><div class=\"flex gap-2\"><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"propType\" class=\"block text-xs text-slate-400 font-semibold\">Tipo de Propiedad</label> <select type=\"text\" name=\"propType\" id=\"propType\" class=\"w-full border border-slate-200 rounded px-2 py-1\" required><option value>Elige un tipo de propiedad</option> <option value=\"casa\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.PropType, "casa") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Casa </option> <option value=\"apartamento\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.PropType, "apartamento") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Apartamento </option> <option value=\"terreno\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.PropType, "terreno") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Terreno </option></select></div><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"lotSize\" class=\"block text-xs text-slate-400 font-semibold\">Construccion (m<sup>2</sup>)</label> <input type=\"text\" name=\"lotSize\" id=\"lotSize\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"90\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%2f", property.LotSize))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 89, Col: 205}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div></div><div class=\"flex gap-2\"><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"beds\" class=\"block text-xs text-slate-400 font-semibold\">Habitaciones</label> <input type=\"text\" name=\"beds\" id=\"beds\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"3\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", property.Beds))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 95, Col: 194}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"baths\" class=\"block text-xs text-slate-400 font-semibold\">Baños</label> <input type=\"text\" name=\"baths\" id=\"baths\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"3\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", property.Beds))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 100, Col: 196}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"sqMt\" class=\"block text-xs text-slate-400 font-semibold\">Superficie (m<sup>2</sup>)</label> <input type=\"text\" name=\"sqMt\" id=\"sqMt\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"90\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%f", property.SqMt))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 105, Col: 195}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" required></div></div><div class=\"flex gap-2\"><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"yearBuilt\" class=\"block text-xs text-slate-400 font-semibold\">Año de Construcción</label> <input type=\"text\" name=\"yearBuilt\" id=\"yearBuilt\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"2010\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", property.YearBuilt))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 112, Col: 212}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></div><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"status\" class=\"block text-xs text-slate-400 font-semibold\">Estatus</label> <select name=\"status\" id=\"status\" class=\"w-full border border-slate-200 rounded px-2 py-1\"><option value=\"disponible\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.Status, "disponible") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Disponible </option> <option value=\"vendida\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.Status, "vendida") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Vendida </option> <option value=\"no_disponible\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.Status, "no_disponible") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">No disponible </option></select></div><div class=\"basis-1/3 grow-0 space-y-1\"><label for=\"contract\" class=\"block text-xs text-slate-400 font-semibold\">Tipo Contrato</label> <select name=\"contract\" id=\"contract\" class=\"w-full border border-slate-200 rounded px-2 py-1\"><option value=\"venta\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.Contract, "venta") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Venta </option> <option value=\"renta\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cmpStr(property.Contract, "renta") {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Renta </option></select></div></div><div class=\"flex gap-2\"><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"lat\" class=\"block text-xs text-slate-400 font-semibold\">Latitud (coordenadas)</label> <input type=\"text\" name=\"lat\" id=\"lat\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100 rounded px-2 py-1\" placeholder=\"24.100100\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%f", property.Lat))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 136, Col: 199}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></div><div class=\"basis-1/2 grow-0 space-y-1\"><label for=\"lon\" class=\"block text-xs text-slate-400 font-semibold\">Longitud (coordenadas)</label> <input type=\"text\" name=\"lon\" id=\"lon\" class=\"w-full border border-rose-700 text-rose-700 bg-rose-100{{else}}border-slate-200{{end}} rounded px-2 py-1\" placeholder=\"-104.200300\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%f", property.Lon))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/edit_property.templ`, Line: 141, Col: 232}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></div></div><div class=\"py-0.5\"></div><div class=\"py-1\"></div><div class=\"flex justify-end\"><button class=\"basis-1/3 px-4 py-2 rounded bg-slate-700 text-stone-50\" type=\"submit\">Enviar</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
