// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vladwithcode/sibra-site/internal/db"
import "github.com/vladwithcode/sibra-site/internal/auth"
import "github.com/vladwithcode/sibra-site/internal/templates/layouts"
import "github.com/vladwithcode/sibra-site/internal/templates/components"

func getRowSpan(idx int) string {
	if idx%5 == 0 {
		return "2"
	}
	return "1"
}

func Index(featProps []*db.Property, newProps []*db.Property, user *auth.Auth) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"relative h-[80vh] xl:h-[60vh] px-4\"><div class=\"absolute z-0 inset-0 p-2\"><img class=\"rounded-md h-full max-w-full object-cover object-left z-0 brightness-75 xl:w-full\" src=\"/static/img/hero.png\" alt=\"Imagen de cabecera\"></div><form action=\"/propiedades\" class=\"relative inset-0 h-full flex flex-col items-stretch justify-center gap-4 px-4 z-10\" id=\"property-search\" data-contract=\"venta\"><h1 class=\"text-light font-bold text-4xl xl:text-4xl 2xl:text-6xl\" style=\"text-shadow: 0 0 10px rgba(22,22,24,1);\">Encuentra tu hogar de ensueño</h1><div class=\"flex items-stretch rounded-lg h-10\"><input class=\"flex-1 basis-full pl-4 pr-2 bg-stone-50 rounded-s-lg outline-indigo-800 placeholder:text-dark/30\" type=\"search\" name=\"search\" id=\"home_search\" placeholder=\"Tierra Blanca, 34139...\"> <button class=\"flex-1 basis-auto bg-secondary px-4 rounded-e-lg\" type=\"submit\"><svg class=\"w-6 h-6 fill-light\"><use href=\"/static/svg/sprites.svg#search\"></use></svg></button></div></form></div><div class=\"px-4 py-16\"><h2 class=\"text-xl font-bold text-dark mb-2\">Propiedades Destacadas</h2><p class=\"text-dark/80 mb-4\">Aquí encontrarás una selección exclusiva de inmuebles que hemos elegido por su excelente ubicación, diseño, y valor.</p><div class=\"grid grid-flow-col grid-rows-2 auto-cols-[17.5rem] h-96 gap-4 overflow-auto py-4 mx-auto\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for idx, prop := range featProps {
				templ_7745c5c3_Err = components.PropertyCardWithRowSpan(prop, getRowSpan(idx)).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div> <div class=\"px-4 py-8 bg-dark space-y-4\"><h2 class=\"text-xl font-bold text-light/90\">Precalificación Infonavit</h2><p class=\"text-light/70\">Te ayudamos con el proceso de tu precalificación Infonavit.</p></div><div class=\"px-4 py-8 space-y-4\"><h2 class=\"text-xl font-bold text-dark/90\">Propiedades Nuevas</h2><p class=\"text-dark/70 mx-auto\">Estas son las propiedades más nuevas en nuestro catalogo.</p><div class=\"flex items-stretch gap-4 overflow-auto py-4 mx-auto\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, prop := range newProps {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"basis-4/5 grow-0 shrink-0 md:basis-72 [&>div]:h-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = components.PropertyCard(prop).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div><form hx-get=\"/propiedades/todas\" class=\"flex flex-wrap items-center justify-center gap-y-8 py-8\"><div class=\"basis-full shrink-0 text-center\"><h2 class=\"text-xl font-bold\">Busca algún vecindario</h2><div class=\"py-1\"></div><p class=\"text-sm text-stone-400\">Ciudad, Colonia, Código Postal</p></div><div class=\"relative w-80 h-12 border border-gray-200 rounded-md focus-within:border-primary\"><input type=\"search\" name=\"search\" id=\"general-search\" class=\"absolute inset-0 pl-2 pr-20 py-4 bg-light basis-3/4 rounded-md outline-primary focus:outline-2\" placeholder=\"Buscar por Ciudad, Código Postal, Estado...\"> <button class=\"absolute z-10 right-0 inset-y-0 text-light/90 bg-secondary rounded-e-md h-full w-20\" type=\"submit\">Buscar</button></div></form><div class=\"py-8\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Sibra Durango", user).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
