// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vladwithcode/sibra-site/internal/auth"

func AdminSidebar(user *auth.Auth) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"relative bg-stone-50 basis-auto shrink-0 grow-0 px-6 border-r border-slate-300 z-30\" id=\"navbar\"><div class=\"relative flex h-14\"><img src=\"/static/img/sibra_logo_256.webp\" alt=\"Logo de sibra durango\" class=\"w-16 h-auto my-auto\" id=\"navbar-logo\"></div><ul class=\"space-y-0.5\"><li class=\"relative text-stone-400 navbar-link\" data-nav-href=\"/admin\"><a href=\"/admin\" class=\"flex items-center text-sm py-2 gap-x-2\"><svg class=\"w-6 h-6 fill-none stroke-current\"><use href=\"/static/svg/cube.svg#cube\"></use></svg><p class=\"\">Inicio</p></a></li><li class=\"relative text-stone-400 navbar-link\" data-nav-href=\"/admin/propiedades\"><a href=\"/admin/propiedades\" class=\"flex items-center text-sm py-2 gap-x-2\"><svg class=\"w-6 h-6 fill-current\"><use href=\"/static/svg/home.svg#home\"></use></svg><p class=\"\">Propiedades</p></a></li><li class=\"relative text-stone-400 navbar-link\" data-nav-href=\"/admin/mi-usuario\"><a href=\"/admin/mi-usuario\" class=\"flex items-center text-sm py-2 gap-x-2\"><svg class=\"w-6 h-6 fill-current\"><use href=\"/static/svg/sprites.svg#user\"></use></svg><p class=\"\">Mi usuario</p></a></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if user != nil && user.Role == "admin" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li class=\"relative text-stone-400 navbar-link\" data-nav-href=\"/admin/usuarios\"><a href=\"/admin/usuarios\" class=\"flex items-center text-sm py-2 gap-x-2\"><svg class=\"w-6 h-6 fill-current\"><use href=\"/static/svg/users.svg#users\"></use></svg><p class=\"\">Usuarios</p></a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
