// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vladwithcode/sibra-site/internal/auth"

func Navigation(user *auth.Auth) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t\tdocument.addEventListener(\"DOMContentLoaded\", () => {\n\t\t\tlet navMobileMenu = document.getElementById(\"nav-mobile-menu\")\n\t\t\tlet navBtnClose = document.getElementById(\"nav-btn-close\")\n\t\t\tlet navBtnOpen = document.getElementById(\"nav-btn-open\")\n\n\t\t\tnavBtnClose.addEventListener(\"click\", () => {\n\t\t\t\tlet tl = gsap.timeline({ ease: \"power2.inOut\", duration: 0.3 })\n\t\t\t\ttl.to(navMobileMenu, { x: \"100%\" })\n\t\t\t})\n\n\t\t\tnavBtnOpen.addEventListener(\"click\", () => {\n\t\t\t\tlet tl = gsap.timeline({ ease: \"power2.inOut\", duration: 0.3 })\n\t\t\t\ttl.to(navMobileMenu, { x: \"0%\" })\n\t\t\t})\n\t\t})\n\t</script><header class=\"h-16 top-0\"><div class=\"h-16 w-full bg-stone-50 fixed flex items-center px-2 z-40\"><a href=\"/\"><img src=\"/static/img/sibra_logo_256.webp\" alt=\"Sibra logo\" class=\"bg-stone-50 w-16 my-auto\"></a><div class=\"xl:px-6\"></div><ul class=\"hidden xl:flex gap-8\"><li class=\"font-semibold\"><a href=\"/\">Inicio</a></li><li class=\"font-semibold\"><a href=\"/propiedades/venta\">Comprar</a></li><li class=\"font-semibold\"><a href=\"/terrenos\">Terrenos y proyectos</a></li></ul><button class=\"shrink space-y-1 my-auto ml-auto xl:hidden\" id=\"nav-btn-open\"><div class=\"w-5 h-0.5 bg-stone-800\"></div><div class=\"w-5 h-0.5 bg-stone-800\"></div><div class=\"w-5 h-0.5 bg-stone-800\"></div></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MobileMenu().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MobileMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"fixed bg-stone-50 inset-0 h-full w-full flex flex-col translate-x-full z-50\" id=\"nav-mobile-menu\"><div class=\"flex items-center justify-between px-4 h-12\"><h2 class=\"text-xl font-bold\">Menu</h2><button class=\"w-fit rounded-full text-stone-950 mr-0\" id=\"nav-btn-close\"><svg class=\"w-4 h-4 fill-current\"><use href=\"/static/svg/times.svg#times\"></use></svg></button></div><div class=\"py-2\"></div><ul class=\"px-4 space-y-4 text-slate-700\"><li class=\"text-lg underline underline-offset-2 font-semibold\"><a href=\"/\">Inicio</a></li><li class=\"text-lg underline underline-offset-2 font-semibold\"><a href=\"/propiedades/venta\">Comprar</a></li><li class=\"text-lg underline underline-offset-2 font-semibold\"><a href=\"/terrenos\">Terrenos y proyectos</a></li></ul><div class=\"mt-auto mb-4 mx-auto\"><img src=\"/static/img/sibra_logo_256.webp\" alt=\"Logo de Sibra durango\" class=\"w-32 h-auto object-center\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
