/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTerrenosRouteImport } from './routes/_public/terrenos'
import { Route as PublicTerminosYCondicionesRouteImport } from './routes/_public/terminos-y-condiciones'
import { Route as PublicPoliticaDePrivacidadRouteImport } from './routes/_public/politica-de-privacidad'
import { Route as PublicNosotrosRouteImport } from './routes/_public/nosotros'
import { Route as PublicIniciarSesionRouteImport } from './routes/_public/iniciar-sesion'
import { Route as PublicInfonavitRouteImport } from './routes/_public/infonavit'
import { Route as PublicFavoritosRouteImport } from './routes/_public/favoritos'
import { Route as PublicContactoRouteImport } from './routes/_public/contacto'
import { Route as PublicProyectosRouteRouteImport } from './routes/_public/proyectos/route'
import { Route as PanelProyectosIndexRouteImport } from './routes/panel/proyectos/index'
import { Route as PanelPropiedadesIndexRouteImport } from './routes/panel/propiedades/index'
import { Route as PanelCitasIndexRouteImport } from './routes/panel/citas/index'
import { Route as ConquistadoresCampanaFbIndexRouteImport } from './routes/conquistadores_/campana-fb.index'
import { Route as PublicProyectosIndexRouteImport } from './routes/_public/proyectos/index'
import { Route as PanelPropiedadesNuevaRouteImport } from './routes/panel/propiedades/nueva'
import { Route as PanelPropiedadesIdRouteImport } from './routes/panel/propiedades/$id'
import { Route as PublicProyectosProjectRouteImport } from './routes/_public/proyectos/$project'
import { Route as PublicPropiedadesListingRouteRouteImport } from './routes/_public/propiedades/_listing/route'
import { Route as PublicPropiedadesDetailRouteRouteImport } from './routes/_public/propiedades/_detail/route'
import { Route as PublicPropiedadesListingIndexRouteImport } from './routes/_public/propiedades/_listing/index'
import { Route as PublicPropiedadesListingContractRouteImport } from './routes/_public/propiedades/_listing/$contract'
import { Route as PublicPropiedadesDetailContractSlugRouteImport } from './routes/_public/propiedades/_detail/$contract.$slug'

const PublicPropiedadesRouteImport = createFileRoute('/_public/propiedades')()

const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPropiedadesRoute = PublicPropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTerrenosRoute = PublicTerrenosRouteImport.update({
  id: '/terrenos',
  path: '/terrenos',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTerminosYCondicionesRoute =
  PublicTerminosYCondicionesRouteImport.update({
    id: '/terminos-y-condiciones',
    path: '/terminos-y-condiciones',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPoliticaDePrivacidadRoute =
  PublicPoliticaDePrivacidadRouteImport.update({
    id: '/politica-de-privacidad',
    path: '/politica-de-privacidad',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicNosotrosRoute = PublicNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicIniciarSesionRoute = PublicIniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicInfonavitRoute = PublicInfonavitRouteImport.update({
  id: '/infonavit',
  path: '/infonavit',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFavoritosRoute = PublicFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactoRoute = PublicContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProyectosRouteRoute = PublicProyectosRouteRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PanelProyectosIndexRoute = PanelProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelPropiedadesIndexRoute = PanelPropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelCitasIndexRoute = PanelCitasIndexRouteImport.update({
  id: '/citas/',
  path: '/citas/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const ConquistadoresCampanaFbIndexRoute =
  ConquistadoresCampanaFbIndexRouteImport.update({
    id: '/conquistadores_/campana-fb/',
    path: '/conquistadores/campana-fb/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicProyectosIndexRoute = PublicProyectosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicProyectosRouteRoute,
} as any)
const PanelPropiedadesNuevaRoute = PanelPropiedadesNuevaRouteImport.update({
  id: '/propiedades/nueva',
  path: '/propiedades/nueva',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelPropiedadesIdRoute = PanelPropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PublicProyectosProjectRoute = PublicProyectosProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => PublicProyectosRouteRoute,
} as any)
const PublicPropiedadesListingRouteRoute =
  PublicPropiedadesListingRouteRouteImport.update({
    id: '/_listing',
    getParentRoute: () => PublicPropiedadesRoute,
  } as any)
const PublicPropiedadesDetailRouteRoute =
  PublicPropiedadesDetailRouteRouteImport.update({
    id: '/_detail',
    getParentRoute: () => PublicPropiedadesRoute,
  } as any)
const PublicPropiedadesListingIndexRoute =
  PublicPropiedadesListingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicPropiedadesListingRouteRoute,
  } as any)
const PublicPropiedadesListingContractRoute =
  PublicPropiedadesListingContractRouteImport.update({
    id: '/$contract',
    path: '/$contract',
    getParentRoute: () => PublicPropiedadesListingRouteRoute,
  } as any)
const PublicPropiedadesDetailContractSlugRoute =
  PublicPropiedadesDetailContractSlugRouteImport.update({
    id: '/$contract/$slug',
    path: '/$contract/$slug',
    getParentRoute: () => PublicPropiedadesDetailRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/panel': typeof PanelRouteRouteWithChildren
  '/proyectos': typeof PublicProyectosRouteRouteWithChildren
  '/contacto': typeof PublicContactoRoute
  '/favoritos': typeof PublicFavoritosRoute
  '/infonavit': typeof PublicInfonavitRoute
  '/iniciar-sesion': typeof PublicIniciarSesionRoute
  '/nosotros': typeof PublicNosotrosRoute
  '/politica-de-privacidad': typeof PublicPoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof PublicTerminosYCondicionesRoute
  '/terrenos': typeof PublicTerrenosRoute
  '/': typeof PublicIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/propiedades': typeof PublicPropiedadesListingRouteRouteWithChildren
  '/proyectos/$project': typeof PublicProyectosProjectRoute
  '/panel/propiedades/$id': typeof PanelPropiedadesIdRoute
  '/panel/propiedades/nueva': typeof PanelPropiedadesNuevaRoute
  '/proyectos/': typeof PublicProyectosIndexRoute
  '/conquistadores/campana-fb': typeof ConquistadoresCampanaFbIndexRoute
  '/panel/citas': typeof PanelCitasIndexRoute
  '/panel/propiedades': typeof PanelPropiedadesIndexRoute
  '/panel/proyectos': typeof PanelProyectosIndexRoute
  '/propiedades/$contract': typeof PublicPropiedadesListingContractRoute
  '/propiedades/': typeof PublicPropiedadesListingIndexRoute
  '/propiedades/$contract/$slug': typeof PublicPropiedadesDetailContractSlugRoute
}
export interface FileRoutesByTo {
  '/contacto': typeof PublicContactoRoute
  '/favoritos': typeof PublicFavoritosRoute
  '/infonavit': typeof PublicInfonavitRoute
  '/iniciar-sesion': typeof PublicIniciarSesionRoute
  '/nosotros': typeof PublicNosotrosRoute
  '/politica-de-privacidad': typeof PublicPoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof PublicTerminosYCondicionesRoute
  '/terrenos': typeof PublicTerrenosRoute
  '/': typeof PublicIndexRoute
  '/panel': typeof PanelIndexRoute
  '/propiedades': typeof PublicPropiedadesListingIndexRoute
  '/proyectos/$project': typeof PublicProyectosProjectRoute
  '/panel/propiedades/$id': typeof PanelPropiedadesIdRoute
  '/panel/propiedades/nueva': typeof PanelPropiedadesNuevaRoute
  '/proyectos': typeof PublicProyectosIndexRoute
  '/conquistadores/campana-fb': typeof ConquistadoresCampanaFbIndexRoute
  '/panel/citas': typeof PanelCitasIndexRoute
  '/panel/propiedades': typeof PanelPropiedadesIndexRoute
  '/panel/proyectos': typeof PanelProyectosIndexRoute
  '/propiedades/$contract': typeof PublicPropiedadesListingContractRoute
  '/propiedades/$contract/$slug': typeof PublicPropiedadesDetailContractSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/panel': typeof PanelRouteRouteWithChildren
  '/_public/proyectos': typeof PublicProyectosRouteRouteWithChildren
  '/_public/contacto': typeof PublicContactoRoute
  '/_public/favoritos': typeof PublicFavoritosRoute
  '/_public/infonavit': typeof PublicInfonavitRoute
  '/_public/iniciar-sesion': typeof PublicIniciarSesionRoute
  '/_public/nosotros': typeof PublicNosotrosRoute
  '/_public/politica-de-privacidad': typeof PublicPoliticaDePrivacidadRoute
  '/_public/terminos-y-condiciones': typeof PublicTerminosYCondicionesRoute
  '/_public/terrenos': typeof PublicTerrenosRoute
  '/_public/': typeof PublicIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/_public/propiedades': typeof PublicPropiedadesRouteWithChildren
  '/_public/propiedades/_detail': typeof PublicPropiedadesDetailRouteRouteWithChildren
  '/_public/propiedades/_listing': typeof PublicPropiedadesListingRouteRouteWithChildren
  '/_public/proyectos/$project': typeof PublicProyectosProjectRoute
  '/panel/propiedades/$id': typeof PanelPropiedadesIdRoute
  '/panel/propiedades/nueva': typeof PanelPropiedadesNuevaRoute
  '/_public/proyectos/': typeof PublicProyectosIndexRoute
  '/conquistadores_/campana-fb/': typeof ConquistadoresCampanaFbIndexRoute
  '/panel/citas/': typeof PanelCitasIndexRoute
  '/panel/propiedades/': typeof PanelPropiedadesIndexRoute
  '/panel/proyectos/': typeof PanelProyectosIndexRoute
  '/_public/propiedades/_listing/$contract': typeof PublicPropiedadesListingContractRoute
  '/_public/propiedades/_listing/': typeof PublicPropiedadesListingIndexRoute
  '/_public/propiedades/_detail/$contract/$slug': typeof PublicPropiedadesDetailContractSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/panel'
    | '/proyectos'
    | '/contacto'
    | '/favoritos'
    | '/infonavit'
    | '/iniciar-sesion'
    | '/nosotros'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/terrenos'
    | '/'
    | '/panel/'
    | '/propiedades'
    | '/proyectos/$project'
    | '/panel/propiedades/$id'
    | '/panel/propiedades/nueva'
    | '/proyectos/'
    | '/conquistadores/campana-fb'
    | '/panel/citas'
    | '/panel/propiedades'
    | '/panel/proyectos'
    | '/propiedades/$contract'
    | '/propiedades/'
    | '/propiedades/$contract/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contacto'
    | '/favoritos'
    | '/infonavit'
    | '/iniciar-sesion'
    | '/nosotros'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/terrenos'
    | '/'
    | '/panel'
    | '/propiedades'
    | '/proyectos/$project'
    | '/panel/propiedades/$id'
    | '/panel/propiedades/nueva'
    | '/proyectos'
    | '/conquistadores/campana-fb'
    | '/panel/citas'
    | '/panel/propiedades'
    | '/panel/proyectos'
    | '/propiedades/$contract'
    | '/propiedades/$contract/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/panel'
    | '/_public/proyectos'
    | '/_public/contacto'
    | '/_public/favoritos'
    | '/_public/infonavit'
    | '/_public/iniciar-sesion'
    | '/_public/nosotros'
    | '/_public/politica-de-privacidad'
    | '/_public/terminos-y-condiciones'
    | '/_public/terrenos'
    | '/_public/'
    | '/panel/'
    | '/_public/propiedades'
    | '/_public/propiedades/_detail'
    | '/_public/propiedades/_listing'
    | '/_public/proyectos/$project'
    | '/panel/propiedades/$id'
    | '/panel/propiedades/nueva'
    | '/_public/proyectos/'
    | '/conquistadores_/campana-fb/'
    | '/panel/citas/'
    | '/panel/propiedades/'
    | '/panel/proyectos/'
    | '/_public/propiedades/_listing/$contract'
    | '/_public/propiedades/_listing/'
    | '/_public/propiedades/_detail/$contract/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  ConquistadoresCampanaFbIndexRoute: typeof ConquistadoresCampanaFbIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/propiedades': {
      id: '/_public/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PublicPropiedadesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terrenos': {
      id: '/_public/terrenos'
      path: '/terrenos'
      fullPath: '/terrenos'
      preLoaderRoute: typeof PublicTerrenosRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terminos-y-condiciones': {
      id: '/_public/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof PublicTerminosYCondicionesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/politica-de-privacidad': {
      id: '/_public/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PublicPoliticaDePrivacidadRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/nosotros': {
      id: '/_public/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof PublicNosotrosRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/iniciar-sesion': {
      id: '/_public/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof PublicIniciarSesionRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/infonavit': {
      id: '/_public/infonavit'
      path: '/infonavit'
      fullPath: '/infonavit'
      preLoaderRoute: typeof PublicInfonavitRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/favoritos': {
      id: '/_public/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof PublicFavoritosRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contacto': {
      id: '/_public/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof PublicContactoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/proyectos': {
      id: '/_public/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof PublicProyectosRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/panel/proyectos/': {
      id: '/panel/proyectos/'
      path: '/proyectos'
      fullPath: '/panel/proyectos'
      preLoaderRoute: typeof PanelProyectosIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/propiedades/': {
      id: '/panel/propiedades/'
      path: '/propiedades'
      fullPath: '/panel/propiedades'
      preLoaderRoute: typeof PanelPropiedadesIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/citas/': {
      id: '/panel/citas/'
      path: '/citas'
      fullPath: '/panel/citas'
      preLoaderRoute: typeof PanelCitasIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/conquistadores_/campana-fb/': {
      id: '/conquistadores_/campana-fb/'
      path: '/conquistadores/campana-fb'
      fullPath: '/conquistadores/campana-fb'
      preLoaderRoute: typeof ConquistadoresCampanaFbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/proyectos/': {
      id: '/_public/proyectos/'
      path: '/'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof PublicProyectosIndexRouteImport
      parentRoute: typeof PublicProyectosRouteRoute
    }
    '/panel/propiedades/nueva': {
      id: '/panel/propiedades/nueva'
      path: '/propiedades/nueva'
      fullPath: '/panel/propiedades/nueva'
      preLoaderRoute: typeof PanelPropiedadesNuevaRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/propiedades/$id': {
      id: '/panel/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/panel/propiedades/$id'
      preLoaderRoute: typeof PanelPropiedadesIdRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_public/proyectos/$project': {
      id: '/_public/proyectos/$project'
      path: '/$project'
      fullPath: '/proyectos/$project'
      preLoaderRoute: typeof PublicProyectosProjectRouteImport
      parentRoute: typeof PublicProyectosRouteRoute
    }
    '/_public/propiedades/_listing': {
      id: '/_public/propiedades/_listing'
      path: ''
      fullPath: '/propiedades'
      preLoaderRoute: typeof PublicPropiedadesListingRouteRouteImport
      parentRoute: typeof PublicPropiedadesRoute
    }
    '/_public/propiedades/_detail': {
      id: '/_public/propiedades/_detail'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PublicPropiedadesDetailRouteRouteImport
      parentRoute: typeof PublicPropiedadesRoute
    }
    '/_public/propiedades/_listing/': {
      id: '/_public/propiedades/_listing/'
      path: '/'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PublicPropiedadesListingIndexRouteImport
      parentRoute: typeof PublicPropiedadesListingRouteRoute
    }
    '/_public/propiedades/_listing/$contract': {
      id: '/_public/propiedades/_listing/$contract'
      path: '/$contract'
      fullPath: '/propiedades/$contract'
      preLoaderRoute: typeof PublicPropiedadesListingContractRouteImport
      parentRoute: typeof PublicPropiedadesListingRouteRoute
    }
    '/_public/propiedades/_detail/$contract/$slug': {
      id: '/_public/propiedades/_detail/$contract/$slug'
      path: '/$contract/$slug'
      fullPath: '/propiedades/$contract/$slug'
      preLoaderRoute: typeof PublicPropiedadesDetailContractSlugRouteImport
      parentRoute: typeof PublicPropiedadesDetailRouteRoute
    }
  }
}

interface PublicProyectosRouteRouteChildren {
  PublicProyectosProjectRoute: typeof PublicProyectosProjectRoute
  PublicProyectosIndexRoute: typeof PublicProyectosIndexRoute
}

const PublicProyectosRouteRouteChildren: PublicProyectosRouteRouteChildren = {
  PublicProyectosProjectRoute: PublicProyectosProjectRoute,
  PublicProyectosIndexRoute: PublicProyectosIndexRoute,
}

const PublicProyectosRouteRouteWithChildren =
  PublicProyectosRouteRoute._addFileChildren(PublicProyectosRouteRouteChildren)

interface PublicPropiedadesDetailRouteRouteChildren {
  PublicPropiedadesDetailContractSlugRoute: typeof PublicPropiedadesDetailContractSlugRoute
}

const PublicPropiedadesDetailRouteRouteChildren: PublicPropiedadesDetailRouteRouteChildren =
  {
    PublicPropiedadesDetailContractSlugRoute:
      PublicPropiedadesDetailContractSlugRoute,
  }

const PublicPropiedadesDetailRouteRouteWithChildren =
  PublicPropiedadesDetailRouteRoute._addFileChildren(
    PublicPropiedadesDetailRouteRouteChildren,
  )

interface PublicPropiedadesListingRouteRouteChildren {
  PublicPropiedadesListingContractRoute: typeof PublicPropiedadesListingContractRoute
  PublicPropiedadesListingIndexRoute: typeof PublicPropiedadesListingIndexRoute
}

const PublicPropiedadesListingRouteRouteChildren: PublicPropiedadesListingRouteRouteChildren =
  {
    PublicPropiedadesListingContractRoute:
      PublicPropiedadesListingContractRoute,
    PublicPropiedadesListingIndexRoute: PublicPropiedadesListingIndexRoute,
  }

const PublicPropiedadesListingRouteRouteWithChildren =
  PublicPropiedadesListingRouteRoute._addFileChildren(
    PublicPropiedadesListingRouteRouteChildren,
  )

interface PublicPropiedadesRouteChildren {
  PublicPropiedadesDetailRouteRoute: typeof PublicPropiedadesDetailRouteRouteWithChildren
  PublicPropiedadesListingRouteRoute: typeof PublicPropiedadesListingRouteRouteWithChildren
}

const PublicPropiedadesRouteChildren: PublicPropiedadesRouteChildren = {
  PublicPropiedadesDetailRouteRoute:
    PublicPropiedadesDetailRouteRouteWithChildren,
  PublicPropiedadesListingRouteRoute:
    PublicPropiedadesListingRouteRouteWithChildren,
}

const PublicPropiedadesRouteWithChildren =
  PublicPropiedadesRoute._addFileChildren(PublicPropiedadesRouteChildren)

interface PublicRouteRouteChildren {
  PublicProyectosRouteRoute: typeof PublicProyectosRouteRouteWithChildren
  PublicContactoRoute: typeof PublicContactoRoute
  PublicFavoritosRoute: typeof PublicFavoritosRoute
  PublicInfonavitRoute: typeof PublicInfonavitRoute
  PublicIniciarSesionRoute: typeof PublicIniciarSesionRoute
  PublicNosotrosRoute: typeof PublicNosotrosRoute
  PublicPoliticaDePrivacidadRoute: typeof PublicPoliticaDePrivacidadRoute
  PublicTerminosYCondicionesRoute: typeof PublicTerminosYCondicionesRoute
  PublicTerrenosRoute: typeof PublicTerrenosRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPropiedadesRoute: typeof PublicPropiedadesRouteWithChildren
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicProyectosRouteRoute: PublicProyectosRouteRouteWithChildren,
  PublicContactoRoute: PublicContactoRoute,
  PublicFavoritosRoute: PublicFavoritosRoute,
  PublicInfonavitRoute: PublicInfonavitRoute,
  PublicIniciarSesionRoute: PublicIniciarSesionRoute,
  PublicNosotrosRoute: PublicNosotrosRoute,
  PublicPoliticaDePrivacidadRoute: PublicPoliticaDePrivacidadRoute,
  PublicTerminosYCondicionesRoute: PublicTerminosYCondicionesRoute,
  PublicTerrenosRoute: PublicTerrenosRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPropiedadesRoute: PublicPropiedadesRouteWithChildren,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface PanelRouteRouteChildren {
  PanelIndexRoute: typeof PanelIndexRoute
  PanelPropiedadesIdRoute: typeof PanelPropiedadesIdRoute
  PanelPropiedadesNuevaRoute: typeof PanelPropiedadesNuevaRoute
  PanelCitasIndexRoute: typeof PanelCitasIndexRoute
  PanelPropiedadesIndexRoute: typeof PanelPropiedadesIndexRoute
  PanelProyectosIndexRoute: typeof PanelProyectosIndexRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelIndexRoute: PanelIndexRoute,
  PanelPropiedadesIdRoute: PanelPropiedadesIdRoute,
  PanelPropiedadesNuevaRoute: PanelPropiedadesNuevaRoute,
  PanelCitasIndexRoute: PanelCitasIndexRoute,
  PanelPropiedadesIndexRoute: PanelPropiedadesIndexRoute,
  PanelProyectosIndexRoute: PanelProyectosIndexRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  ConquistadoresCampanaFbIndexRoute: ConquistadoresCampanaFbIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
