CREATE TABLE IF NOT EXISTS (
    id               varchar(),
    address          varchar(),
    description      varchar(),
    city             varchar(),
    state            varchar(),
    zip              varchar(),
    nb_hood           varchar(),
    country          varchar(),
    price             float64,
    prop_type         varchar(),
    contract         varchar(),
    beds              int,
    baths             int,
    sq_mt              float64,
    lot_size           float64,
    listing_date       date,
    year_built         int,
    status           varchar(),
    coords            GEOMETRY(point, 4326),
    features          map[string]any,
    lat               float64,
    lon               float64,
    featured          bool DEFAULT false,
    featured_expires_at timestamp with time zone,
    main_img          varchar(),
    agent            varchar(),
    slug             varchar(),
    images            varchar(255)[],
    agent_data         *_agent_data
);
