CREATE TABLE IF NOT EXISTS properties (
    id uuid PRIMARY KEY,
    address varchar(256) NOT NULL,
    description varchar(512) DEFAULT '',
    city varchar(128) NOT NULL,
    state varchar(128) NOT NULL,
    zip varchar(5) DEFAULT '',
    nb_hood varchar(128) DEFAULT '',
    country varchar(128) DEFAULT '',
    price NUMERIC(12,4) DEFAULT CAST(0.0 as NUMERIC),
    property_type varchar(128) NOT NULL,
    contract varchar(16) NOT NULL,
    beds int NOT NULl,
    baths int NOT NULL,
    square_mt real NOT NULL,
    lot_size real NOT NULL,
    listing_date date DEFAULT NOW(),
    year_built int DEFAULT 0,
    coords GEOMETRY(Point, 4326),
    status varchar(64) NOT NULL,
    lat DOUBLE PRECISION DEFAULT 0.0,
    lon DOUBLE PRECISION DEFAULT 0.0,
    featured bool DEFAULT false,
    featured_expires_at timestamp with time zone DEFAULT NOW(),
    main_img varchar(256) DEFAULT '',
    imgs varchar(256)[],
    agent uuid NOT NULL,
    slug varchar(512),
    features jsonb,

    -- features          map[string]any,

    FOREIGN KEY (agent) REFERENCES users
);
